#pragma once
#include "Exercise01.h"
#include "Exercise02.h"
#include "Exercise03.h"
#include "Exercise04.h"
#include "Exercise05.h"
#include "Exercise06.h"
#include "Exercise07.h"
#include "Exercise08.h"
#include "Exercise09.h"
#include "Exercise10.h"
#include "Exercise11.h"
#include "Exercise12.h"
#include "Exercise13.h"
#include "Exercise14.h"
#include "Exercise15.h"
#include "Exercise16.h"
#include "Exercise17.h"
#include "Exercise18.h"
#include "Exercise19.h"
#include "Exercise20.h"
#include "Exercise21.h"
#include "Exercise22.h"
#include "Exercise23.h"
#include "Exercise24.h"
#include "Exercise25.h"
#include "Exercise26.h"
#include "Exercise27.h"
#include "Exercise28.h"
#include "Exercise29.h"
#include "Exercise30.h"
#include "Exercise31.h"
#include "Exercise32.h"
#include "Exercise33.h"
#include "Exercise34.h"
#include "Exercise35.h"
#include "Exercise36.h"
#include "Exercise37.h"
#include "Exercise38.h"
#include "Exercise39.h"
#include "Exercise40.h"
#include "Exercise41.h"
#include "Exercise42.h"
#include "Exercise43.h"
#include "Exercise44.h"
#include "Exercise45.h"
#include "Exercise46.h"
#include "Exercise47.h"
#include "Exercise48.h"
#include "Exercise49.h"
#include "Exercise50.h"
#include "Exercise51.h"
#include "Exercise52.h"
#include "Exercise53.h"
#include "Exercise54.h"
#include "Exercise55.h"
#include "Exercise56.h"
#include "../01.DataStructure&Algorithm/01.Sort&Search/Exercise00_SortTools.h"

void test_nowcoder(void) {
	//if (TestExercise13()) {
	//	Println("success!");
	//}
	//else {
	//	Println("failed!");
	//}

	TestExercise33();
}